name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Run shellcheck
      run: shellcheck -S warning -e SC2155 umpf
