name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Run shellcheck
      run: shellcheck -S warning -e SC2155 umpf

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install Meson & Ninja
      run: pip install meson ninja

    - name: Setup builddir
      run: meson setup builddir/

    - name: Run tests
      run: meson test -C builddir/

    - name: Dump test log
      if: failure()
      run: cat builddir/meson-logs/testlog.txt
